summon fireball ~2 ~50 ~ {ExplosionPower:0b,acceleration_power:0.1d,Motion:[0.0,-0.1,0.0],Passengers:[{id:"minecraft:sheep",DeathLootTable:"h",Team:"player",Health:25f,Color:13b,attributes:[{id:"minecraft:generic.knockback_resistance",base:1},{id:"minecraft:generic.max_health",base:15},{id:"minecraft:generic.scale",base:0.75}]}],Item:{id:"minecraft:cobblestone",count:1}}
summon fireball ~-2 ~50 ~ {ExplosionPower:0b,acceleration_power:0.1d,Motion:[0.0,-0.1,0.0],Passengers:[{id:"minecraft:sheep",DeathLootTable:"h",Team:"player",Health:25f,Color:13b,attributes:[{id:"minecraft:generic.knockback_resistance",base:1},{id:"minecraft:generic.max_health",base:15},{id:"minecraft:generic.scale",base:0.75}]}],Item:{id:"minecraft:stone",count:1}}
summon fireball ~ ~50 ~2 {ExplosionPower:0b,acceleration_power:0.1d,Motion:[0.0,-0.1,0.0],Passengers:[{id:"minecraft:sheep",DeathLootTable:"h",Team:"player",Health:25f,Color:13b,attributes:[{id:"minecraft:generic.knockback_resistance",base:1},{id:"minecraft:generic.max_health",base:15},{id:"minecraft:generic.scale",base:0.75}]}],Item:{id:"minecraft:stone",count:1}}
summon fireball ~ ~50 ~-2 {ExplosionPower:0b,acceleration_power:0.1d,Motion:[0.0,-0.1,0.0],Passengers:[{id:"minecraft:sheep",DeathLootTable:"h",Team:"player",Health:25f,Color:13b,attributes:[{id:"minecraft:generic.knockback_resistance",base:1},{id:"minecraft:generic.max_health",base:15},{id:"minecraft:generic.scale",base:0.75}]}],Item:{id:"minecraft:end_stone",count:1}}
summon fireball ~2 ~75 ~ {ExplosionPower:0b,acceleration_power:0.1d,Motion:[0.0,-0.1,0.0],Passengers:[{id:"minecraft:sheep",DeathLootTable:"h",Team:"player",Health:25f,Color:13b,attributes:[{id:"minecraft:generic.knockback_resistance",base:1},{id:"minecraft:generic.max_health",base:15},{id:"minecraft:generic.scale",base:0.75}]}],Item:{id:"minecraft:stone",count:1}}
summon fireball ~-2 ~75 ~ {ExplosionPower:0b,acceleration_power:0.1d,Motion:[0.0,-0.1,0.0],Passengers:[{id:"minecraft:sheep",DeathLootTable:"h",Team:"player",Health:25f,Color:13b,attributes:[{id:"minecraft:generic.knockback_resistance",base:1},{id:"minecraft:generic.max_health",base:15},{id:"minecraft:generic.scale",base:0.75}]}],Item:{id:"minecraft:diorite",count:1}}
summon fireball ~ ~75 ~2 {ExplosionPower:0b,acceleration_power:0.1d,Motion:[0.0,-0.1,0.0],Passengers:[{id:"minecraft:sheep",DeathLootTable:"h",Team:"player",Health:25f,Color:13b,attributes:[{id:"minecraft:generic.knockback_resistance",base:1},{id:"minecraft:generic.max_health",base:15},{id:"minecraft:generic.scale",base:0.75}]}],Item:{id:"minecraft:stone",count:1}}
summon fireball ~ ~75 ~-2 {ExplosionPower:0b,acceleration_power:0.1d,Motion:[0.0,-0.1,0.0],Passengers:[{id:"minecraft:sheep",DeathLootTable:"h",Team:"player",Health:25f,Color:13b,attributes:[{id:"minecraft:generic.knockback_resistance",base:1},{id:"minecraft:generic.max_health",base:15},{id:"minecraft:generic.scale",base:0.75}]}],Item:{id:"minecraft:stone",count:1}}
summon fireball ~2 ~100 ~ {ExplosionPower:0b,acceleration_power:0.1d,Motion:[0.0,-0.1,0.0],Passengers:[{id:"minecraft:sheep",DeathLootTable:"h",Team:"player",Health:25f,Color:13b,attributes:[{id:"minecraft:generic.knockback_resistance",base:1},{id:"minecraft:generic.max_health",base:15},{id:"minecraft:generic.scale",base:0.75}]}],Item:{id:"minecraft:ancient_debris",count:1}}
summon fireball ~-2 ~100 ~ {ExplosionPower:0b,acceleration_power:0.1d,Motion:[0.0,-0.1,0.0],Passengers:[{id:"minecraft:sheep",DeathLootTable:"h",Team:"player",Health:25f,Color:13b,attributes:[{id:"minecraft:generic.knockback_resistance",base:1},{id:"minecraft:generic.max_health",base:15},{id:"minecraft:generic.scale",base:0.75}]}],Item:{id:"minecraft:stone",count:1}}
summon fireball ~ ~100 ~2 {ExplosionPower:0b,acceleration_power:0.1d,Motion:[0.0,-0.1,0.0],Passengers:[{id:"minecraft:sheep",DeathLootTable:"h",Team:"player",Health:25f,Color:13b,attributes:[{id:"minecraft:generic.knockback_resistance",base:1},{id:"minecraft:generic.max_health",base:15},{id:"minecraft:generic.scale",base:0.75}]}],Item:{id:"minecraft:stone",count:1}}
summon fireball ~ ~100 ~-2 {ExplosionPower:0b,acceleration_power:0.1d,Motion:[0.0,-0.1,0.0],Passengers:[{id:"minecraft:sheep",DeathLootTable:"h",Team:"player",Health:25f,Color:13b,attributes:[{id:"minecraft:generic.knockback_resistance",base:1},{id:"minecraft:generic.max_health",base:15},{id:"minecraft:generic.scale",base:0.75}]}],Item:{id:"minecraft:stone",count:1}}
tellraw @a ["<",{"selector":"@s"},"> ","space sheep."]
scoreboard players set @s egocd 800