


execute unless entity @e[team=!blagh,type=!item,type=!minecraft:experience_orb,type=!#minecraft:arrows,type=!#minecraft:impact_projectiles,type=!minecraft:block_display,type=!minecraft:marker,type=!player] run effect give @e[tag=healthtracker] minecraft:instant_health 1 2 true
execute unless entity @e[tag=healthtracker] unless entity @e[team=!blagh,type=!item,type=!minecraft:experience_orb,type=!#minecraft:arrows,type=!#minecraft:impact_projectiles,type=!minecraft:block_display,type=!minecraft:marker,type=!player] run summon minecraft:cow 3.40 -60.00 9.92 {Brain: {memories: {}}, HurtByTimestamp: 66943, Invulnerable: 0b, FallFlying: 0b, ForcedAge: 0, PortalCooldown: 0, AbsorptionAmount: 0.0f, FallDistance: 0.0f, active_effects: [{duration: -1, show_icon: 0b, amplifier: 4b, id: "minecraft:regeneration", show_particles: 0b}, {duration: -1, show_icon: 0b, amplifier: 2b, id: "minecraft:slowness", show_particles: 0b}, {duration: -1, show_icon: 0b, amplifier: 1b, id: "minecraft:speed", show_particles: 0b}], InLove: 0, DeathTime: 0s, HandDropChances: [0.085f, 0.085f], PersistenceRequired: 0b, Tags: ["collective.checked", "lha", "healthtracker"], Age: 0, AngerTime: 501, AngryAt: [I; -440280982, -771342065, -1791373925, -242476481], Motion: [-0.043651561195198196d, -0.0784000015258789d, 6.823212045638534E-4d], Health: 400f, LeftHanded: 0b, Air: 300s, OnGround: 1b, Glowing: 1b, Rotation: [88.030594f, -30.0f], HandItems: [{components: {"minecraft:enchantments": {levels: {"minecraft:knockback": 3}}}, count: 1, id: "minecraft:stick"}, {}], ArmorDropChances: [0.085f, 0.085f, 0.085f, 0.085f], Fire: -1s, ArmorItems: [{}, {}, {}, {}], CanPickUpLoot: 0b, attributes: [{id: "minecraft:generic.armor", base: 30.0d}, {id: "minecraft:generic.attack_damage", base: 20.0d}, {id: "minecraft:generic.max_health", base: 400.0d}, {id: "minecraft:generic.movement_speed", modifiers: [{amount: 0.4000000059604645d, id: "minecraft:effect.speed", operation: "add_multiplied_total"}, {amount: -0.45000001788139343d, id: "minecraft:effect.slowness", operation: "add_multiplied_total"}], base: 0.20000000298023224d}, {id: "minecraft:generic.scale", base: 2.0d}, {id: "minecraft:generic.follow_range", modifiers: [{amount: 0.005866018387887538d, id: "minecraft:random_spawn_bonus", operation: "add_multiplied_base"}], base: 16.0d}, {id: "minecraft:generic.knockback_resistance", base: 1.0d}], HurtTime: 0s}
execute unless entity @e[team=!blagh,type=!item,type=!minecraft:experience_orb,type=!#minecraft:arrows,type=!#minecraft:impact_projectiles,type=!minecraft:block_display,type=!minecraft:marker,type=!player] run kill @e[tag=lhasummon]

execute as @e[tag=bossguy] at @s store result score @s hp run data get entity @s Health
execute as @e[tag=phantomboss] at @s if score @s hp matches ..100 run damage @s 25 minecraft:generic_kill
execute as @e[tag=phantomboss] at @s if score @s hp matches ..100 run summon phantom ~ ~ ~ {Team:"antiblagh",Size:0}

#execute unless entity @e[type=cow,tag=cm5] unless entity @e[tag=!adminfrfr,team=!blagh,type=!item,type=!minecraft:experience_orb,type=!#minecraft:arrows,type=!#minecraft:impact_projectiles,type=!minecraft:block_display,type=!minecraft:marker] run summon cow 15.49 -59.50 1.93 {Team:"blagh",Tags:["cm5"]}
#execute unless entity @e[type=cow,tag=cm4] unless entity @e[tag=!adminfrfr,team=!blagh,type=!item,type=!minecraft:experience_orb,type=!#minecraft:arrows,type=!#minecraft:impact_projectiles,type=!minecraft:block_display,type=!minecraft:marker] run summon cow 15.49 -59.50 1.93 {Team:"blagh",Tags:["cm4"]}
#execute unless entity @e[tag=!adminfrfr,team=!blagh,type=!item,type=!minecraft:experience_orb,type=!#minecraft:arrows,type=!#minecraft:impact_projectiles,type=!minecraft:block_display,type=!minecraft:marker] unless entity @e[type=cow,tag=cm3] run summon cow 15.49 -59.50 1.93 {Team:"blagh",Tags:["cm3"]}
#execute unless entity @e[tag=!adminfrfr,team=!blagh,type=!item,type=!minecraft:experience_orb,type=!#minecraft:arrows,type=!#minecraft:impact_projectiles,type=!minecraft:block_display,type=!minecraft:marker] unless entity @e[type=cow,tag=cm2] run summon cow 15.49 -59.50 1.93 {Team:"blagh",Tags:["cm2"]}
#execute unless entity @e[type=cow,tag=cm1] unless entity @e[tag=!adminfrfr,team=!blagh,type=!item,type=!minecraft:experience_orb,type=!#minecraft:arrows,type=!#minecraft:impact_projectiles,type=!minecraft:block_display,type=!minecraft:marker] run summon cow 15.49 -59.50 1.93 {Team:"blagh",Tags:["cm1"]}

#execute unless entity @e[tag=healthtracker] unless entity @e[team=!blagh] run summon minecraft:cow 16.21 -60.00 14.13 {Brain: {memories: {}}, HurtByTimestamp: 3743, Invulnerable: 0b, FallFlying: 0b, ForcedAge: 0, PortalCooldown: 0, AbsorptionAmount: 0.0f, FallDistance: 0.0f, active_effects: [{duration: -1, show_icon: 0b, amplifier: 2b, id: "minecraft:slowness", show_particles: 0b}, {duration: -1, show_icon: 0b, amplifier: 1b, id: "minecraft:speed", show_particles: 0b}, {duration: -1, show_icon: 0b, amplifier: 4b, id: "minecraft:regeneration", show_particles: 0b}], InLove: 0, DeathTime: 0s, HandDropChances: [0.085f, 0.085f], PersistenceRequired: 0b, Tags: ["collective.checked", "healthtracker"], Age: 0, AngerTime: 526, AngryAt: [I; 1285906882, -882032501, -1754364520, -1241071651], Motion: [0.005036987618845014d, -0.0784000015258789d, 0.08142786805624008d], Health: 301.0f, LeftHanded: 0b, Air: 300s, OnGround: 1b, Glowing: 1b, Rotation: [215.86374f, 4.9903736f], HandItems: [{components: {"minecraft:enchantments": {levels: {"minecraft:knockback": 3}}}, count: 1, id: "minecraft:stick"}, {}], ArmorDropChances: [0.085f, 0.085f, 0.085f, 0.085f], Fire: -1s, ArmorItems: [{}, {}, {}, {}], CanPickUpLoot: 0b, attributes: [{id: "minecraft:generic.attack_damage", base: 20.0d}, {id: "minecraft:generic.follow_range", modifiers: [{amount: 0.005866018387887538d, id: "minecraft:random_spawn_bonus", operation: "add_multiplied_base"}], base: 16.0d}, {id: "minecraft:generic.knockback_resistance", base: 1.0d}, {id: "minecraft:generic.movement_speed", modifiers: [{amount: 0.4000000059604645d, id: "minecraft:effect.speed", operation: "add_multiplied_total"}, {amount: -0.45000001788139343d, id: "minecraft:effect.slowness", operation: "add_multiplied_total"}], base: 0.20000000298023224d}, {id: "minecraft:generic.scale", base: 2.0d}, {id: "minecraft:generic.max_health", base: 400.0d}, {id: "minecraft:generic.armor", base: 30.0d}], HurtTime: 7s}

execute as @e[tag=batgrenade] at @s facing entity @n[team=!antiblagh,tag=!adminfrfr] eyes run tp @s ^ ^ ^0.2
execute as @e[tag=batgrenade] at @s positioned ~-0.25 ~-0.25 ~-0.25 if entity @e[team=!antiblagh,tag=!adminfrfr,dx=0.5,dz=0.5,dy=0.5] run summon creeper ~ ~ ~ {Invulnerable:1b,Team:"antiblagh",Fuse:0,CustomName:'"Bat grenade"'}
execute as @e[tag=batgrenade] at @s positioned ~-0.25 ~-0.25 ~-0.25 if entity @e[team=!antiblagh,tag=!adminfrfr,dx=0.5,dz=0.5,dy=0.5] run kill @s


team join blagh @e[tag=healthtracker,team=!antiblagh]